In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pandas import read_csv, set_option
from pandas.plotting import scatter_matrix

In [2]:
fraud =  read_csv("creditcard.csv")
fraud

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

# Understanding of DataSet

1. View the Raws

In [3]:
set_option('display.width',100)
fraud.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

2.  Dimension of the DataSet

In [4]:
fraud.shape

(284807, 31)

3. Data Types of the attributes

In [5]:
fraud.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

Our observations are as follows

NaN values do not present in the data set. Because of the Non-Null Count and number of rows in the dataset match.

There are 29 Input Variables and 1 Output Variable (Class)

The data type of all the input variables is float64 whereas the data type of out variable (Class) is int64

4. Presence of Null Values in Dataset

In [6]:
fraud.isnull().sum().sum()

0

The dataset does not contain any null values

5. Statistical Analysis

In [7]:
set_option('precision',2)
fraud.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.00,2.85e+05,2.85e+05,2.85e+05,2.85e+05,2.85e+05,2.85e+05,2.85e+05,2.85e+05,2.85e+05,...,2.85e+05,2.85e+05,2.85e+05,2.85e+05,2.85e+05,2.85e+05,2.85e+05,2.85e+05,284807.00,2.85e+05
mean,94813.86,3.92e-15,5.68e-16,-8.76e-15,2.81e-15,-1.55e-15,2.04e-15,-1.70e-15,-1.89e-16,-3.15e-15,...,1.47e-16,8.04e-16,5.28e-16,4.46e-15,1.43e-15,1.70e-15,-3.66e-16,-1.22e-16,88.35,1.73e-03
std,47488.15,1.96e+00,1.65e+00,1.52e+00,1.42e+00,1.38e+00,1.33e+00,1.24e+00,1.19e+00,1.10e+00,...,7.35e-01,7.26e-01,6.24e-01,6.06e-01,5.21e-01,4.82e-01,4.04e-01,3.30e-01,250.12,4.15e-02
min,0.00,-5.64e+01,-7.27e+01,-4.83e+01,-5.68e+00,-1.14e+02,-2.62e+01,-4.36e+01,-7.32e+01,-1.34e+01,...,-3.48e+01,-1.09e+01,-4.48e+01,-2.84e+00,-1.03e+01,-2.60e+00,-2.26e+01,-1.54e+01,0.00,0.00e+00
25%,54201.50,-9.20e-01,-5.99e-01,-8.90e-01,-8.49e-01,-6.92e-01,-7.68e-01,-5.54e-01,-2.09e-01,-6.43e-01,...,-2.28e-01,-5.42e-01,-1.62e-01,-3.55e-01,-3.17e-01,-3.27e-01,-7.08e-02,-5.30e-02,5.60,0.00e+00
50%,84692.00,1.81e-02,6.55e-02,1.80e-01,-1.98e-02,-5.43e-02,-2.74e-01,4.01e-02,2.24e-02,-5.14e-02,...,-2.95e-02,6.78e-03,-1.12e-02,4.10e-02,1.66e-02,-5.21e-02,1.34e-03,1.12e-02,22.00,0.00e+00
75%,139320.50,1.32e+00,8.04e-01,1.03e+00,7.43e-01,6.12e-01,3.99e-01,5.70e-01,3.27e-01,5.97e-01,...,1.86e-01,5.29e-01,1.48e-01,4.40e-01,3.51e-01,2.41e-01,9.10e-02,7.83e-02,77.16,0.00e+00
max,172792.00,2.45e+00,2.21e+01,9.38e+00,1.69e+01,3.48e+01,7.33e+01,1.21e+02,2.00e+01,1.56e+01,...,2.72e+01,1.05e+01,2.25e+01,4.58e+00,7.52e+00,3.52e+00,3.16e+01,3.38e+01,25691.16,1.00e+00

In [8]:
# T work as Transpose
fraud.describe().T

           count      mean       std     min       25%       50%        75%        max
Time    284807.0  9.48e+04  47488.15    0.00  54201.50  8.47e+04  139320.50  172792.00
V1      284807.0  3.92e-15      1.96  -56.41     -0.92  1.81e-02       1.32       2.45
V2      284807.0  5.68e-16      1.65  -72.72     -0.60  6.55e-02       0.80      22.06
V3      284807.0 -8.76e-15      1.52  -48.33     -0.89  1.80e-01       1.03       9.38
V4      284807.0  2.81e-15      1.42   -5.68     -0.85 -1.98e-02       0.74      16.88
V5      284807.0 -1.55e-15      1.38 -113.74     -0.69 -5.43e-02       0.61      34.80
V6      284807.0  2.04e-15      1.33  -26.16     -0.77 -2.74e-01       0.40      73.30
V7      284807.0 -1.70e-15      1.24  -43.56     -0.55  4.01e-02       0.57     120.59
V8      284807.0 -1.89e-16      1.19  -73.22     -0.21  2.24e-02       0.33      20.01
V9      284807.0 -3.15e-15      1.10  -13.43     -0.64 -5.14e-02       0.60      15.59
V10     284807.0  1.77e-15      1.09  -24.59     -0.54 -9.29e-02       0.45      23.75
V11     284807.0  9.29e-16      1.02   -4.80     -0.76 -3.28e-02       0.74      12.02
V12     284807.0 -1.80e-15      1.00  -18.68     -0.41  1.40e-01       0.62       7.85
V13     284807.0  1.67e-15      1.00   -5.79     -0.65 -1.36e-02       0.66       7.13
V14     284807.0  1.48e-15      0.96  -19.21     -0.43  5.06e-02       0.49      10.53
V15     284807.0  3.50e-15      0.92   -4.50     -0.58  4.81e-02       0.65       8.88
V16     284807.0  1.39e-15      0.88  -14.13     -0.47  6.64e-02       0.52      17.32
V17     284807.0 -7.47e-16      0.85  -25.16     -0.48 -6.57e-02       0.40       9.25
V18     284807.0  4.26e-16      0.84   -9.50     -0.50 -3.64e-03       0.50       5.04
V19     284807.0  9.02e-16      0.81   -7.21     -0.46  3.73e-03       0.46       5.59
V20     284807.0  5.13e-16      0.77  -54.50     -0.21 -6.25e-02       0.13      39.42
V21     284807.0  1.47e-16      0.73  -34.83     -0.23 -2.95e-02       0.19      27.20
V22     284807.0  8.04e-16      0.73  -10.93     -0.54  6.78e-03       0.53      10.50
V23     284807.0  5.28e-16      0.62  -44.81     -0.16 -1.12e-02       0.15      22.53
V24     284807.0  4.46e-15      0.61   -2.84     -0.35  4.10e-02       0.44       4.58
V25     284807.0  1.43e-15      0.52  -10.30     -0.32  1.66e-02       0.35       7.52
V26     284807.0  1.70e-15      0.48   -2.60     -0.33 -5.21e-02       0.24       3.52
V27     284807.0 -3.66e-16      0.40  -22.57     -0.07  1.34e-03       0.09      31.61
V28     284807.0 -1.22e-16      0.33  -15.43     -0.05  1.12e-02       0.08      33.85
Amount  284807.0  8.83e+01    250.12    0.00      5.60  2.20e+01      77.16   25691.16
Class   284807.0  1.73e-03      0.04    0.00      0.00  0.00e+00       0.00       1.00

We can see that the data for the variables from V1 to V28 is already scaled and cleaned. So there is no need for a data cleaning process in this case

# Response Variable Analysis
Fraud vs Non-Fraud

In [9]:
class_names = {0:'Not Fraud', 1:"Fraud"}
print(fraud.Class.value_counts().rename(index = class_names))

Not Fraud    284315
Fraud           492
Name: Class, dtype: int64

 You may notice the imbalance in data labels. The majority of the transections(data)
are nonfraud

# Data Visualization 

We can draw the scatterplot marix and heatmap But the variables description i snot give
in this case, we will not gain any usefull insights from the plot. Hence we can skip this step

# Data Cleaning 
This data is alreay in a cleaned format without an empty rows or columns. Data 
Cleansing or categorization is not required in this case.

# Train-Test split 

TO Train and Test of data before fitting into ML MODEL is important. Because 
We would like to to train the model by fitting the training data. But to test the data, we should use the data that is new to the model. Then only we would be able to calculate the perfomance of the model on the unseen data.

In [10]:
from sklearn.model_selection import train_test_split
y= fraud["Class"]
X = fraud.loc[:, fraud.columns != 'Class']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=1/3,random_state=42, stratify=y)

# Data Modeling

In this step, we will evaluate different machine learning models
we will use Linear  as well as NON-Linear Algorithms for this evaluation

# Linear Algorithms 

Logistic Regression(LR) and Linear Discriminant Analysis(LDA)

# Non-Linear Algorithms

Classification and Regression Tree(CART) and K-NN

# Logistic Regression

In [11]:
#Import Library for Accuracy Score
from sklearn.metrics import accuracy_score

#Import Library for Logistic Regression
from sklearn.linear_model import LogisticRegression

#Initialize the Logistic Regression Classifier
logisreg = LogisticRegression()

#Train the model using Training Dataset
logisreg.fit(X_train, y_train)

# Prediction using test data
y_pred = logisreg.predict(X_test)

# Calculate Model accuracy by comparing y_test and y_pred
acc_logisreg = round( accuracy_score(y_test, y_pred) * 100, 2 )
print( 'Accuracy of Logistic Regression model : ', acc_logisreg )

Accuracy of Logistic Regression model :  99.91

C:\Users\AdityaRaj Sharma\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

# Linear Discriminant Analysis

In [12]:
#Import Library for Accuracy Score
from sklearn.metrics import accuracy_score

#Import Library for Logistic Regression
from sklearn.linear_model import LogisticRegression

#Initialize the Logistic Regression Classifier
logisreg = LogisticRegression()

#Train the model using Training Dataset
logisreg.fit(X_train, y_train)

# Prediction using test data
y_pred = logisreg.predict(X_test)

# Calculate Model accuracy by comparing y_test and y_pred
acc_logisreg = round( accuracy_score(y_test, y_pred) * 100, 2 )
print( 'Accuracy of Logistic Regression model : ', acc_logisreg )

Accuracy of Logistic Regression model :  99.91

C:\Users\AdityaRaj Sharma\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

# Gaussian Naive Bayes

In [18]:
#Import Library for Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB

#Initialize the Gaussian Naive Bayes Classifier
model = GaussianNB()

#Train the model using Training Dataset
model.fit(X_train, y_train)

# Prediction using test data
y_pred = model.predict(X_test)

# Calculate Model accuracy by comparing y_test and y_pred
acc_ganb = round( accuracy_score(y_test, y_pred) * 100, 2 )
print( 'Accuracy of Gaussian Naive Bayes : ', acc_ganb )

Accuracy of Gaussian Naive Bayes :  99.28

# Decision Tree

In [14]:
#Import Library for Decision Tree
from sklearn.tree import DecisionTreeClassifier

#Initialize the Decision Tree Classifier
model = DecisionTreeClassifier()

#Train the model using Training Dataset
model.fit(X_train, y_train)

# Prediction using test data
y_pred = model.predict(X_test)

# Calculate Model accuracy by comparing y_test and y_pred
acc_dtree = round( accuracy_score(y_test, y_pred) * 100, 2 )
print( 'Accuracy of  Decision Tree Classifier : ', acc_dtree)

Accuracy of  Decision Tree Classifier :  99.91

# Random Forest

In [15]:
#Import Library for Random Forest
from sklearn.ensemble import RandomForestClassifier

#Initialize the Random Forest
model = RandomForestClassifier()

#Train the model using Training Dataset
model.fit(X_train, y_train)

# Prediction using test data
y_pred = model.predict(X_test)

# Calculate Model accuracy by comparing y_test and y_pred
acc_rf = round( accuracy_score(y_test, y_pred) * 100, 2 )
print( 'Accuracy of  Random Forest : ', acc_rf)

Accuracy of  Random Forest :  99.96

# Support Vector Machine Model

In [16]:
#Import Library for Support Vector Machine Model
from sklearn import svm

#Initialize the Support Vector Classifier
model = svm.SVC()

#Train the model using Training Dataset
model.fit(X_train, y_train)

# Prediction using test data
y_pred = model.predict(X_test)

# Calculate Model accuracy by comparing y_test and y_pred
acc_svc = round( accuracy_score(y_test, y_pred) * 100, 2 )
print( 'Accuracy of  Support Vector Classifier: ', acc_svc)

Accuracy of  Support Vector Classifier:  99.83

# K Nearest Neighbour Model

In [17]:
#Import Library for K Nearest Neighbour Model
from sklearn.neighbors import KNeighborsClassifier

#Initialize the K Nearest Neighbour Model with Default Value of K=5
model = KNeighborsClassifier()  

#Train the model using Training Dataset
model.fit(X_train, y_train)

# Prediction using test data
y_pred = model.predict(X_test)

# Calculate Model accuracy by comparing y_test and y_pred
acc_knn = round( accuracy_score(y_test, y_pred) * 100, 2 )
print( 'Accuracy of  KNN Classifier: ', acc_knn)

Accuracy of  KNN Classifier:  99.83